require 'formulita_backend/models/championship'
require 'formulita_backend/models/qualifying_result'
require 'formulita_backend/models/race'
require 'formulita_backend/models/race_result'
require 'formulita_backend/models/driver'
require 'formulita_backend/models/team'
